apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: vasman-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.6
        ports:
        - containerPort: 80
        securityContext:
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
