name: Build and Push Docker Image

on:
  workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # Replace with your region

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  


      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${{ secrets.ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com

      - name: Build and push image
        run: |
          docker build -t vasman-test .
          docker push public.ecr.aws/k3f5q1f1/vasman-test:latest
