name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Replace with your region

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: docker login -u srini19081998 -p Hihihi98!

      - name: Build  and Push Images
        run: |
          docker build -t srini19081998/microservices-demo-auth:latest auth/.
          docker push srini19081998/microservices-demo-auth:latest
          docker build -t srini19081998/microservices-demo-account:latest account/.
          docker push srini19081998/microservices-demo-account:latest
          # Add more build and push commands for other services
